---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install essential packages
      package:
        name:
          - htop
          - vim-nox
          - gpaste
          - flameshot
          - make
