---
- hosts: localhost
  connection: local
  become: true

  tasks:
    # Install essential packages
    - name: install essential packages
      package:
        name:
          - dconf-cli
          - python3-psutil
          - htop
          - vim-nox
          - gpaste
          - flameshot
          - make

    # Configure wallpaper
    - name: copy wallpaper file
      copy:
        src: files/spider-verse-wallpaper.jpg
        dest: /usr/share/backgrounds/spider-verse-wallpaper.jpg
        owner: root
        group: root

    - name: set wallpaper
      become_user: jfgomez
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/spider-verse-wallpaper.jpg'"

    - name: set wallpaper position
      become_user: jfgomez
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    # Configure auto-provision for ansible runs
    - name: add ansible user
      user:
        name: velociraptor
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_velociraptor
        dest: /etc/sudoers.d/velociraptor
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: velociraptor
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/jfgomez0912/ansible_desktop.git

    # Install Google Chrome
    - name: software | google-chrome | add repository key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: software | google-chrome | add repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: google-chrome
      register: chrome_repo

    - name: software | google-chrome | update sources (repo added or changed)
      apt:
        update_cache: yes
      changed_when: False
      when: chrome_repo.changed

    - name: software | google-chrome | install package
      apt:
        name: google-chrome-stable

    # Install VSCode
    - name: software | vscode | add repository key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: software | vscode | add repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        filename: vscode
      register: vscode_repo

    - name: software | vscode | update sources (repo added or changed)
      apt:
        update_cache: yes
      changed_when: False
      when: vscode_repo.changed

    - name: software | vscode | install package
      apt:
        name: code

    # Install Spotify
    - name: software | spotify | install package
      snap:
        name: spotify

    # Install Terraform
    - name: software | terraform | install binary
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

    # Install Docker
    - name: install docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    # Install AWS CLI
    # Install Postman
    # Install DBeaver
    # Define Start Menu Programs
    # Create Key Shortcuts for GPaste and Super+E
    # Set GPaste and Flamshor to run at start
    # Customize terminal colors
