---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install essential packages
      package:
        name:
          - dconf-cli
          - htop
          - vim-nox
          - gpaste
          - flameshot
          - make

    - name: copy wallpaper file
      copy:
        src: files/spider-verse-wallpaper.jpg
        dest: /usr/share/backgrounds/spider-verse-wallpaper.jpg
        owner: root
        group: root

    - name: set wallpaper
      become_user: jfgomez
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/spider-verse-wallpaper.jpg'"

    - name: set wallpaper position
      become_user: jfgomez
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
